analyzeNoBlockers = "- seems like standups does not contain any prolem or blocker. Remember that problems help us grow. No problems == no development. Dont hesitate to report them"
analyzeNoLinks = "- seems like standups does not contain any links, that means that probably no work was done or no research was conducted. Poor you."
analyzeNoQuestions = "- seems like standups does not contain any questions. Internship is made up of questions, so ask as many as you can!"
analyzeNoSize = "- seems like standups does is either small or too large. Appropriate size is about 80 - 200 words."
analyzeNoTags = "- seems like standups does not contain any tags. If you want your mentors to notice you, tag them right away!"
analyzePRAsignee = "- need to add who is assigned to implement changes to this PR"
analyzePRConflicts = "- no way to merge it. Fix conflicts first"
analyzePRDescription = "- need more words in PR Description field"
analyzePRLinks = "- need to include links on tickets which would be closed by this PR"
analyzePRReviewer = "- no reviewers tagged, please, assign at least one"
analyzePRSize = "- PR contains too much changes. Divide it and resend."
analyzePRWIP = "- PR contains unfinished work, please, finish it and resend the link"
badPR = "- bad PR, pay attention to the following advises: \\n"
checkStandup = "Good standup, post it to the group!"
closingPart = "I will kick you from the group if you miss 3 standups. In case of any unexpected behaviour DM @anatoliyfedorenko"
createStanduperFailed = "Could not add you to standup team"
failedLeaveStanupers = "Could not remove you from standup team"
failedRecognizeTZ = "Failed to recognize new TZ you entered, double check the tz name and try again"
failedRemoveStandupDeadline = "Could not remove standup deadline"
failedUpdateStandupDeadline = "Could not edit standup deadline"
failedUpdateTZ = "Failed to update Timezone"
goodPR = "- good PR, review indeed needed!"
greatStandup = "Standup accepted and it looks awesome!"
helpText = "List of awailable commands:\n\t\t\t/join - add you to standup team\n\t\t\t/show - shows who is in standup team\n\t\t\t/leave - leave standup team to stop submit standups\n\t\t\t/edit_deadline - Set standups deadline (formats: 13:50, 1:50pm)\n\t\t\t/show_deadline - Show current standup deadline\n\t\t\t/group_tz - Change group time zone (defaulting to : Asia/Bishkek)\n\t\t\t/tz - Change individual Time Zone (defaulting to: Asia/Bishkek)\n\t\t\n\t\t\tLooking forward for your standups! Message @anatoliyfedorenko in case of any unexpected behaviour"
leaveStanupers = "You no longer have to submit standups, thanks for all your standups and messages"
noProblemsMention = "- no 'problems' keywords detected: {{.Keywords}}"
noStandupDeadline = "Standup deadline is not set"
noTodayMention = "- no 'today' keywords detected: {{.Keywords}}"
noYesterdayMention = "- no 'yesterday' keywords detected: {{.Keywords}}"
notStandup = "Seems like this is not a standup, double check keywords for errors \\n\\n"
notStanduper = "You do not standup yet"
notifyNonReporters = "Attention, {{.Intern}}! you have just missed the deadline! submit standups ASAP. {{.Skips}} skips left \\n\\n"
removeStandupDeadline = "Standup deadline removed"
standupDeadline = "Standup deadline set for everyday at {{.Deadline}} exept weekeds"
standupDeadlinePart = "Submit your standups before, {{.Deadline}}! You do not have to write standups on weekends"
standupUpdated = "Standup was successfully updated!"
standupsCheckPart = "If you would like to validate your standup, direct message me with the text and I can check it to give advises. \\n"
updateStandupDeadline = "Edited standup deadline, new deadline is {{.Deadline}}"
updateTZ = "Group timezone is updated, new TZ is {{.TZ}}"
updateUserTZ = "your timezone is updated, new TZ is {{.TZ}}"
warnNonReporters = "Attention, {{.Intern}} {{.Warn}} minutes till deadline, submit standups ASAP. {{.Skips}} skips left \\n\\n"
welcomeMessage = "Hello! I will help you to not forget about standups and write them properly. tag @anatoliyfedorenko if you find any bug or unexpected behaviour :)"
welcomeNoDedline = "Welcome to the standup team, no standup deadline has been setup yet"
welcomePart = "Hello, @{{.Intern}}! Welcome to {{.GroupName}}"
welcomeWithDedline = "Welcome to the standup team, please, submit your standups no later than {{.Deadline}}"
youAlreadyStandup = "You already a part of standup team"

[acceptStandupWithAdvises]
few = "Standup is accepted, but let me give you several advises: \\n {{.Advises}}"
many = "Standup is accepted, but let me give you several advises: \\n {{.Advises}}"
one = "Standup is accepted, but let me give you one advise: \\n {{.Advises}}"
other = "Standup is accepted, but let me give you several advises: \\n {{.Advises}}"
two = "Standup is accepted, but let me give you two advises: \\n {{.Advises}}"

[checkStandupWithAdvises]
few = "Standup is going to be more usefull with several advises: \\n {{.Advises}}"
many = "Standup is going to be more usefull with several advises: \\n {{.Advises}}"
one = "Standup is going to be more usefull with one advise: \\n {{.Advises}}"
other = "Standup is going to be more usefull with several advises: \\n {{.Advises}}"
two = "Standup is going to be more usefull with two advises: \\n {{.Advises}}"
