[analyzeNoBlockers]
hash = "sha1-aedec71919630864ecaf7e8af462c790ac0a13af"
other = "- Кажется в стендапе нет или мало проблем. Проблемы и всё, что мешает это показатель роста. Если их нет, это плохо. не бойся об этом говорить"

[analyzeNoLinks]
hash = "sha1-c3f750829123d654db50584067247508ec9e3041"
other = "- Кажется в стендапе нет ни одной ссылки. Желательно отправлять ссылки на PRы либо на изученные ресурсы"

[analyzeNoQuestions]
hash = "sha1-d98699e1d4898ca9445af3daf6f209c6e8c168e6"
other = "- Кажется в стендапе не задано вопросов. На стажировке надо задавать вопросы, самое лучше место это общий чат и стендапы. Без вопросов нет развития"

[analyzeNoSize]
hash = "sha1-31a010735979000ed3947ccd7c2c198cc09ce122"
other = "- Подумай над размером стендапа. Напишешь мало - непонятно, грач, без уважения. Много - тяжело читать. Оптимально от 80 до 200 слов"

[analyzeNoTags]
hash = "sha1-98c8cfb93d369dc6eaa8c9cdbf18305d0e2967da"
other = "- Кажется в стендапе нет тегов. Тегай менторов, чтобы получить их опыт, иначе прогресс будет медленный"

[analyzePRAsignee]
hash = "sha1-d332a08e33f553b7cfd51006ea040f46510b1176"
other = "- нужно назначить человека, который работает над PRом"

[analyzePRConflicts]
hash = "sha1-8f8ff97663bb62971ac044871cdcb75abf3df908"
other = "- нельзя смержить код в PR, сначала надо решить все конфликты"

[analyzePRDescription]
hash = "sha1-4785e9a64f59345277b486cd4a737ecaedc9a8f1"
other = "- нужно больше слов в описании к PR"

[analyzePRLinks]
hash = "sha1-627352c1915d3026d54f82a72d7e3e2c388ba09d"
other = "- желательно добавить в описание ссылки на задачи, которые закроет этот PR"

[analyzePRReviewer]
hash = "sha1-eb683d76347f5253d9499138f4129d36c81e29ef"
other = "- нет назначеных на ревью людей, лучше отметить кого-нибудь"

[analyzePRSize]
hash = "sha1-f4e39b0f948bb7f30df7d8fbaa5c160267b4e8d5"
other = "- в PR очень много изменений, попробуй его разделить."

[analyzePRWIP]
hash = "sha1-701ddb91c869576bb99794a040bc13f592471fce"
other = "- PR содержит незавершенную работу, сначала надо закончить её"

[badPR]
hash = "sha1-7df112903b8328763bd8fe09d1295fbb4156cd23"
other = "- плохой PR, Обрати внимание на советы: \\n"

[checkStandup]
hash = "sha1-a7eb979ca3562c99e48d8f411692b50a29bb7cbf"
other = "Хороший стендап! Можно постить в группу"

[createStanduperFailed]
hash = "sha1-0c2c7f510c062191a09701b7d62a1f7ce754054b"
other = "не удалось добавить вас в команду стендаперов"

[failedLeaveStanupers]
hash = "sha1-c7374272c4a00a4dc1b1d8f6ac46c75a5e2f8129"
other = "Не удалось убрать вас из стендаперов"

[failedRecognizeTZ]
hash = "sha1-a31bd479bb70e1789ef1b53beaca1f4ee22931c5"
other = "Failed to recognize new TZ you entered, double check the tz name and try again"

[failedRemoveOnbordingMessage]
hash = "sha1-b3f3c8d2c638036ea7efa947e33016c5b4abe305"
other = "Не удалось очистить онбординг сообщение"

[failedRemoveStandupDeadline]
hash = "sha1-20b5795d14f0bb6c66529d224bb91271b86470f9"
other = "Не удалось убрать крайний срок сдачи стендапов"

[failedUpdateLanguage]
hash = "sha1-297a4b55a5f69a07b7a242f0fb9029e82b2c6fdc"
other = "Не удалось обновить язык группы"

[failedUpdateOnbordingMessage]
hash = "sha1-c3176e08ad0d2db0d5999da8ec55a9aec8bd63f1"
other = "Не удалось обновить онбординг сообщение"

[failedUpdateStandupDeadline]
hash = "sha1-f216fc7d2c8ea294b46d350e21eac60153f85465"
other = "Не смог обновить срок сдачи стендапов"

[failedUpdateSubmissionDays]
hash = "sha1-e2159ec09877592680b60a35ab6859065db57bff"
other = "Не смог обновить дни сдачи стендапов"

[failedUpdateTZ]
hash = "sha1-ce1fbc677f0e60cb0930a0daffc6cf3effeea900"
other = "Не удалось обновить часовой пояс"

[goodPR]
hash = "sha1-5379ae28a52e0459744cb0e23f01df2556b87b30"
other = "- хороший PR, нужно сделать ревью!"

[greatStandup]
hash = "sha1-4efb9052545374bb15381f6c6560a36f0e3a6621"
other = "Стендап принят, хорошего дня!"

[helpText]
hash = "sha1-e230ab554bb22b973544e0804722eb5fd34b1b46"
other = "Чтобы написать стендап тегни меня в сообщении с ключевыми словами. Напиши мне в личку текст стендапа, чтобы я сказал какие ключевые слова пропущены. Жду ваших стендапов! Напиши @anatoliyfedorenko в случае любых проблем связанных со мной, отправляйте запросы на доработку в этот репозиторий https://github.com/maddevsio/mad-telegram-standup-bot/issues"

[leaveStanupers]
hash = "sha1-aa349b49e8cfa8132c055dabfa72436424101503"
other = "Вам больше не нужно сдавать стендапы, спасибо за все ваши сообщения!"

[noProblemsMention]
hash = "sha1-fd5ada3d46270c013bc30233b94e7c12a304fbc0"
other = "- нет ключевых слов блока 'проблемы' {{.Keywords}}"

[noStandupDeadline]
hash = "sha1-a1e4959733ee1f6f257bc4e5b81be38cf58ecc6b"
other = "Крайний срок сдачи стендапов не установлен"

[noTodayMention]
hash = "sha1-a414039575828892ae739899cf3303299a3094f7"
other = "- нет ключевых слов блока 'сегодня': {{.Keywords}}"

[noYesterdayMention]
hash = "sha1-bdff0c3bc740bf4fb242f13c35b3f78894e49b0e"
other = "- нет ключевых слов блока 'вчера': {{.Keywords}}"

[notStandup]
hash = "sha1-5aef6e43386c994b89fe7dac6996efeb3c1f7fef"
other = "Кажется, что это вообще не стендап, перепроверь ключевые слова. "

[notStanduper]
hash = "sha1-1c88a37c3eb3279a3f0cf6b8cb6f0a0ee737f61b"
other = "Вы еще не стендапите"

[notifyNonReporters]
hash = "sha1-2b0f062e311665168ba0888d8bcb00034399a3d5"
other = "Внимание, {{.Standuper}}! ты пропустил стендап! пожалуйста, сдай его как можно скорее, команда ждёт!"

[presenceDuration]
few = "в проекте {{.Days}} дня, "
hash = "sha1-c72b016f4534d8b5c283526aa48b9e078ec75dbc"
many = "в проекте {{.Days}} дней, "
one = "в проекте {{.Days}} день, "
other = "в проекте {{.Days}} дня, "

[removeOnbordingMessage]
hash = "sha1-6c0324b9a86975d90e6d45cf8b56166f13d6fdfc"
other = "Убрал приветственное сообщение"

[removeStandupDeadline]
hash = "sha1-6444dd89936abbd9a8cc0a99e16394a0ca1b9dc6"
other = "Крайний срок сдачи стендапов отменён"

[showNoStandupers]
hash = "sha1-e8aef7674bf966b36bed44a562a63103a54c327e"
other = "Никто не стендапит, /join чтобы начать стендапить"

[showStandupers]
hash = "sha1-24fc4df2ea53bf88ae1a22b3f5531ca618ba619b"
other = "Стендапят:"

[standupDeadline]
hash = "sha1-c707504adacbeeefba770d008756f533bde9c3fd"
other = "Standup deadline set at {{.Deadline}} on {{.Weekdays}}"

[standupUpdated]
hash = "sha1-273954d72c1f9d0289de4deb0c141877bf9a6796"
other = "Стендап успешно обновлен"

[updateGroupLanguage]
hash = "sha1-bda4f21c0e3e9a604a768553e73aab90688ca8e9"
other = "Язык группы обновлен"

[updateGroupSubmissionDays]
hash = "sha1-a24b70f5da913cc02935beb9f4e3ae77df9fe1c4"
other = "Дни сдачи стендапов успешно обновлены"

[updateOnbordingMessage]
hash = "sha1-0d62596bbc0ad2de2b996a603266fee31f5680e2"
other = "Привественное сообщение обновлено"

[updateStandupDeadline]
hash = "sha1-bfd3f195e36e139ad0643664950c0dd74da9fde2"
other = "Крайний срок сдачи стендапов изменён на {{.Deadline}}"

[updateTZ]
hash = "sha1-ec2a5b809759814ed5dbe1020c591babb0443c28"
other = "Часовой пояс группы обновлен на {{.TZ}}"

[updateUserTZ]
hash = "sha1-32171fe98964d605c38ef1811374a3f4000cdf70"
other = "ваш часовой пояс обновлен на {{.TZ}}"

[warnNonReporters]
hash = "sha1-484719e443af4604fd036059c07ecff7bab901dc"
other = "Внимание, {{.Standuper}}, {{.Warn}} минут до дедлайна, скорее пиши стендап и не подводи команду."

[welcomeBack]
hash = "sha1-c4a23c9d48392e38f4a383f624cad582eeb3a185"
other = "Добро пожаловать обратно в команду! Рад видеть и с нетерпением жду стендапов!"

[welcomeNoDedline]
hash = "sha1-e57fbe3ef11584376832f8981aa8728f0b291e32"
other = "Добро пожаловать в стендап команду, дедлайна пока не установлено"

[welcomePart]
hash = "sha1-63bb77b34d9aef8073b822f011f3fbfd4f4a76a0"
other = "Привет, @{{.Intern}}! Добро пожаловать в {{.GroupName}}"

[welcomeWithDedline]
hash = "sha1-9c0fb2113888323c689d5d30bd4641f5caf57505"
other = "Добро пожаловать! Жду стендапы от вас до {{.Deadline}} каждый день кроме выходных"

[youAlreadyStandup]
hash = "sha1-3a2af532b419e8e30e0668a9880805acd5a2a8be"
other = "Вы уже стендапите"
