analyzeNoBlockers = "- seems like standups does not contain any prolem or blocker. Remember that problems help us grow. No problems == no development. Dont hesitate to report them"
analyzeNoLinks = "- seems like standups does not contain any links, that means that probably no work was done or no research was conducted. Poor you."
analyzeNoQuestions = "- seems like standups does not contain any questions. Internship is made up of questions, so ask as many as you can!"
analyzeNoSize = "- seems like standups does is either small or too large. Appropriate size is about 80 - 200 words."
analyzeNoTags = "- seems like standups does not contain any tags. If you want your mentors to notice you, tag them right away!"
analyzePRAsignee = "- need to add who is assigned to implement changes to this PR"
analyzePRConflicts = "- no way to merge it. Fix conflicts first"
analyzePRDescription = "- need more words in PR Description field"
analyzePRLinks = "- need to include links on tickets which would be closed by this PR"
analyzePRReviewer = "- no reviewers tagged, please, assign at least one"
analyzePRSize = "- PR contains too much changes. Divide it and resend."
analyzePRWIP = "- PR contains unfinished work, please, finish it and resend the link"
badPR = "- bad PR, pay attention to the following advises: \\n"
checkStandup = "Good standup, post it to the group!"
createStanduperFailed = "Could not add you to standup team"
failedLeaveStanupers = "Could not remove you from standup team"
failedRecognizeTZ = "Failed to recognize new TZ you entered, double check the tz name and try again"
failedRemoveOnbordingMessage = "Could not remove remove onbording message"
failedRemoveStandupDeadline = "Could not remove standup deadline"
failedUpdateLanguage = "Could not edit group language"
failedUpdateOnbordingMessage = "Could not edit onbording message"
failedUpdateStandupDeadline = "Could not edit standup deadline"
failedUpdateSubmissionDays = "Could not edit standup submission days"
failedUpdateTZ = "Failed to update Timezone"
goodPR = "- good PR, review indeed needed!"
greatStandup = "Standup accepted and it looks awesome!"
helpText = "In order to submit a standup, tag me and write a message with keywords. Direct message me to see the list of keywords needed. Loking forward for your standups! Message @anatoliyfedorenko in case of any unexpected behaviour, submit issues to https://github.com/maddevsio/mad-internship-bot/issues"
leaveStanupers = "You no longer have to submit standups, thanks for all your standups and messages"
noProblemsMention = "- no 'problems' keywords detected: {{.Keywords}}"
noStandupDeadline = "Standup deadline is not set"
noTodayMention = "- no 'today' keywords detected: {{.Keywords}}"
noYesterdayMention = "- no 'yesterday' keywords detected: {{.Keywords}}"
notStandup = "Seems like this is not a standup, double check keywords for errors. "
notStanduper = "You do not standup yet"
notifyNonReporters = "Attention, {{.Intern}}! you have just missed the deadline! submit standups ASAP. {{.Skips}} skips left"
removeOnbordingMessage = "Onbording message removed"
removeStandupDeadline = "Standup deadline removed"
showNoStandupers = "No standupers in the team, /join to start standuping"
showStandupers = "Standupers:"
standupDeadline = "Standup deadline set at {{.Deadline}} on {{.Weekdays}}"
standupUpdated = "Standup was successfully updated!"
updateGroupLanguage = "Group language updated"
updateGroupSubmissionDays = "Group Standup submission days updated"
updateOnbordingMessage = "Onbording message updated"
updateStandupDeadline = "Edited standup deadline, new deadline is {{.Deadline}}"
updateTZ = "Group timezone is updated, new TZ is {{.TZ}}"
updateUserTZ = "your timezone is updated, new TZ is {{.TZ}}"
warnNonReporters = "Attention, {{.Intern}} {{.Warn}} minutes till deadline, submit standups ASAP. {{.Skips}} skips left"
welcomeBack = "Welcome back! Glad to see you again, and looking forward to your standups"
welcomeNoDedline = "Welcome to the standup team, no standup deadline has been setup yet"
welcomePart = "Hello, @{{.Intern}}! Welcome to {{.GroupName}}"
welcomeWithDedline = "Welcome to the standup team, please, submit your standups no later than {{.Deadline}}"
youAlreadyStandup = "You already a part of standup team"

[missedStandups]
few = "missed standups: {{.missedTimes}} times"
many = "missed standups: {{.missedTimes}} times"
one = "missed only deadline"
other = "missed standups: {{.missedTimes}} times"
two = "missed standups: {{.missedTimes}} times"

[presenceDuration]
few = "{{.Days}} days in the project, "
many = "{{.Days}} days in the project, "
one = "{{.Days}} day in the project, "
other = "{{.Days}} days in the project, "
two = "{{.Days}} days in the project, "
