version: '2'

services:

  db:
    image: mysql:5.7
    volumes:
      - "database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: telegram
      MYSQL_USER: telegram
      MYSQL_PASSWORD: telegram

  bot:
    build: .
    restart: on-failure
    links:
      - db:db
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Bishkek
      DATABASE_URL: telegram:telegram@tcp(db:3306)/telegram?parseTime=true&charset=utf8mb4&collation=utf8mb4_unicode_ci
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DEBUG: ${DEBUG}
      ONBORDING_MESSAGE: ${ONBORDING_MESSAGE}
    depends_on:
      - db

volumes:
  database: