version: '2'

networks:
  comedian_comedian:
    external: true

services:
  bot:
    container_name: mad-telegram-standup-bot
    image: maddevsio/mad-telegram-standup-bot:latest
    restart: on-failure
    environment:
      TZ: Asia/Bishkek
      DATABASE_URL: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(mad-telegram-standup-bot-mysql:3306)/${MYSQL_DATABASE}?parseTime=true&charset=utf8mb4&collation=utf8mb4_unicode_ci
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DEBUG: ${DEBUG}
    networks:
      - comedian_comedian